Homework 2
================
Andrea Vasquez
10/04/2026

- [Problem 1](#problem-1)
  - [1.1 Data import and cleaning + brief
    description](#11-data-import-and-cleaning--brief-description)
  - [1.2 Answering questions](#12-answering-questions)
  - [1.3 Reformat data](#13-reformat-data)
  - [1.4 Questions about train A](#14-questions-about-train-a)
- [Problem 2](#problem-2)
  - [2.1 Data import and cleaning](#21-data-import-and-cleaning)
  - [2.2 Data set description](#22-data-set-description)
  - [2.3 Answer to Questions:](#23-answer-to-questions)
- [Problem 3](#problem-3)
  - [3.1 Data import + clean +
    questions](#31-data-import--clean--questions)
  - [3.2 Data import and clean of amyloid data
    set](#32-data-import-and-clean-of-amyloid-data-set)
  - [3.3 Checking whether participants appear in only one
    dataset](#33-checking-whether-participants-appear-in-only-one-dataset)
  - [3.4 Combining dataset](#34-combining-dataset)

# Problem 1

### 1.1 Data import and cleaning + brief description

``` r
NYC_transit_df = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  na = c("NA", "", "."),
    col_types = cols(
      Route8 = col_character(),
      Route9 = col_character(),
      Route10 = col_character(),
      Route11 = col_character()))|> 
  janitor::clean_names()|> 
  select(line, station_name, station_latitude, station_longitude,
         starts_with("route"), entry, vending, entrance_type, ada) |> 
  mutate(entry = recode_values(entry, "YES" ~ TRUE, "NO" ~ FALSE))

NYC_transit_df
```

    ## # A tibble: 1,868 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <chr>, route9 <chr>, route10 <chr>, route11 <chr>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

The NYC transit dataset contains information on each subway entrance and
exit. After cleaning, it has 1868 rows and 19 columns, of which 15 are
character variables (line, station name, routes 1–11, vending, and
entrance type), 2 are logical variables (entry and ADA compliance), and
2 are numeric variables (station latitude and longitude). To clean the
data, I imported the file specifying that blank cells be treated as
missing and that routes 8-11 be read as character variables. These
columns contain numbered trans and would otherwise be read as numeric,
even though the values are route name and not true numbers. I then
cleaned the variables names, retained only the variables of interest,
and converted the entry variable from character to logical. Given that
route spread across 11 columns, we can conclude that this data is not
tidy. To be tidy, there should be a single column for the variable
route.

### 1.2 Answering questions

- There are 465 distinct stations.

- In total, 84 stations are ADA compliant.

- Among entrances/exits without vending, 37.7% allow entrance.

### 1.3 Reformat data

``` r
NYC_transit_tidy = 
  NYC_transit_df |> 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name")|> 
  drop_na(route_name)

NYC_transit_tidy
```

    ## # A tibble: 4,270 × 10
    ##    line     station_name station_latitude station_longitude entry vending
    ##    <chr>    <chr>                   <dbl>             <dbl> <lgl> <chr>  
    ##  1 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  2 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  3 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  4 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  5 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  6 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  7 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  8 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  9 4 Avenue 45th St                  40.6             -74.0 TRUE  YES    
    ## 10 4 Avenue 45th St                  40.6             -74.0 TRUE  YES    
    ## # ℹ 4,260 more rows
    ## # ℹ 4 more variables: entrance_type <chr>, ada <lgl>, route_number <chr>,
    ## #   route_name <chr>

### 1.4 Questions about train A

There are 60 stations serving the A train, of which 17 are ADA
compliant.

# Problem 2

### 2.1 Data import and cleaning

``` r
Mr_Wheel_df = 
  readxl::read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N742",
    na = c("NA", "", "."))|> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    year = as.integer(year), 
    trash_wheel = "Mr_Trash") |> 
  relocate(trash_wheel)

Prof_Wheel_df = 
  readxl::read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M139",
    na = c("NA", "", ".", "dive"))|> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(
    year = as.integer(year), 
    trash_wheel = "Professor_Trash") |> 
  relocate(trash_wheel)

Gwynnda_df = 
  readxl::read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:L394",
    na = c("NA", "", "."))|> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(
    year = as.integer(year), 
    trash_wheel = "Gwynnda") |> 
  relocate(trash_wheel)

trash_wheel_df = 
  bind_rows(Mr_Wheel_df, Prof_Wheel_df, Gwynnda_df)

trash_wheel_df
```

    ## # A tibble: 1,269 × 15
    ##    trash_wheel dumpster month  year date                weight_tons
    ##    <chr>          <dbl> <chr> <int> <dttm>                    <dbl>
    ##  1 Mr_Trash           1 May    2014 2014-05-16 00:00:00        4.31
    ##  2 Mr_Trash           2 May    2014 2014-05-16 00:00:00        2.74
    ##  3 Mr_Trash           3 May    2014 2014-05-16 00:00:00        3.45
    ##  4 Mr_Trash           4 May    2014 2014-05-17 00:00:00        3.1 
    ##  5 Mr_Trash           5 May    2014 2014-05-17 00:00:00        4.06
    ##  6 Mr_Trash           6 May    2014 2014-05-20 00:00:00        2.71
    ##  7 Mr_Trash           7 May    2014 2014-05-21 00:00:00        1.91
    ##  8 Mr_Trash           8 May    2014 2014-05-28 00:00:00        3.7 
    ##  9 Mr_Trash           9 June   2014 2014-06-05 00:00:00        2.52
    ## 10 Mr_Trash          10 June   2014 2014-06-11 00:00:00        3.76
    ## # ℹ 1,259 more rows
    ## # ℹ 9 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

### 2.2 Data set description

The combined dataset contains 1269 observations and 15 variables. The
data were collected from 2014 to 2026, and each observation represents a
dumpster filled by one of three trash wheels: Mr. Trash Wheel (740
dumpsters), Professor Trash Wheel (137 dumpsters), and Gwynnda (392
dumpsters). Some key variables include the trash wheel that collected
the dumpster (`trash_wheel`), the dumpster number and the date of
collection, the weight (in tons) and volume (in cubic yards) of trash
collected, as well as the count of specific items, such as plastic
bottles, polystyrene, cigarette butts, plastic bags, sports balls, and
wrappers. Some variables are not recorded for every wheel. For example,
sports balls are only available for Mr. Trash Wheel.

It is important to note that given some quality issues present in the
raw data, the combined data may not look exactly the same. For instance,
the Gwynnda sheet skips the dumpster numbers 373 to 379 and dumpster 21
appears twice, resulting in a total number of dumpster (392) different
from the highest recorded number (398). In the Professor Trash Wheel
sheet, one entry had the text “dive” in place of a plastic bottle count
and so was treated as a missing value.

### 2.3 Answer to Questions:

For available data, Professor Trash Wheel collected a total of 294.96
tons of trash. Gwynnda collected 18,120 cigarette butts in June of 2022.

# Problem 3

### 3.1 Data import + clean + questions

``` r
baseline_df = 
  read_csv("data/MCI_baseline.csv", skip = 1, na = c("NA", "", ".")) |> 
  janitor::clean_names() |> 
  mutate(
    sex = recode_values(sex, 1 ~ "male", 0 ~ "female"),
    apoe4 = recode_values(apoe4, 1 ~ "carrier", 0 ~ "non_carrier")) |>
  filter(is.na(age_at_onset) | age_at_onset > current_age)
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
baseline_df
```

    ## # A tibble: 479 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ##  1     1        63.1 female        16 carrier             NA  
    ##  2     2        65.6 female        20 carrier             NA  
    ##  3     3        62.5 male          16 carrier             66.8
    ##  4     4        69.8 female        16 non_carrier         NA  
    ##  5     5        66   male          16 non_carrier         68.7
    ##  6     6        62.5 male          16 non_carrier         NA  
    ##  7     7        66.5 male          18 non_carrier         74  
    ##  8     8        67.2 female        18 non_carrier         NA  
    ##  9     9        66.7 female        16 non_carrier         NA  
    ## 10    10        64.1 female        18 non_carrier         NA  
    ## # ℹ 469 more rows

Some of the crucial steps to import and clean this data was to indicate
the rows and columns to be included (skipping the first row that did not
provided data entry) and specify that missing values should have NA as
their entry. The variables sex and apoe4 needed to be recoded to avoid
confusion with the meaning of 1 and 0. Finally, the data was filtered to
remove entries that did not meet the inclusion criteria. In other words,
patients who had their MCI onset before the study began (age at onset ≤
current age).

Overall, this dataset includes 479 participants and 6variable (ID,
baseline age, sex, years of education, APOE4 carrier status, and age at
MCI onset, which is missing for those who never developed MCI).

In total, 479 participants were recruited, of whom 93 developed MCI
during follow-up. The average baseline age was 65 years. Among women in
the study, 30% are APOE4 carriers.

### 3.2 Data import and clean of amyloid data set

``` r
amyloid_df = 
  read_csv("data/mci_amyloid.csv", skip = 1, na = c("NA", "", ".", "Na")) |> 
  janitor::clean_names() |> 
  rename(id = study_id) |> 
  pivot_longer(
    baseline:time_8,
    names_to = "visit",
    values_to = "amyloid_ratio")
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
amyloid_df
```

    ## # A tibble: 2,435 × 3
    ##       id visit    amyloid_ratio
    ##    <dbl> <chr>            <dbl>
    ##  1     1 baseline         0.111
    ##  2     1 time_2          NA    
    ##  3     1 time_4           0.109
    ##  4     1 time_6           0.105
    ##  5     1 time_8           0.107
    ##  6     2 baseline         0.107
    ##  7     2 time_2           0.109
    ##  8     2 time_4           0.109
    ##  9     2 time_6           0.106
    ## 10     2 time_8           0.107
    ## # ℹ 2,425 more rows

This dataset contains the amyloid 42/40 ratio measured for each
participant at up to five visits: baseline and 2, 4, 6, and 8 years
after baseline. A few steps were needed to clean the data. The first row
of the file is a description and not the variables names, so it was
skipped during import. Several observations had “NA” or “Na” entered in
place of a ratio, and these were treated as missing. The variable
`study_id` was renamed to `id` to match the baseline dataset. The data
were not tidy, since there was a separate column for each visit, so I
reorganized them to a long format with one row per participant per
visit. The resulting dataset has 2435 rows and 3 variables
(`id`,`visit`, and `amyloid_ratio`), covering 487 participants.

### 3.3 Checking whether participants appear in only one dataset

``` r
baseline_only_df = 
  baseline_df |> 
  filter(!(id %in% pull(amyloid_df, id)))

amyloid_only_df = 
  amyloid_df |> 
  filter(!(id %in% pull(baseline_df, id))) |> 
  distinct(id)
```

There are 8 participants that appear only on the baseline dataset and 16
that appear only in the amyloid dataset. This indicates that 8
participants have baseline information but no amyloid measurements, and
the 16 have amyloid measurements but no baseline record. If these
participants were kept when combining the data, they would have missing
values for all of the variables from the other dataset, so only those
who appear in both datasets should be included in the combined data.

### 3.4 Combining dataset

``` r
mci_df = inner_join(baseline_df, amyloid_df, by = "id")

write_csv(mci_df, "data/mci_combined.csv")
```

The combined dataset includes only the 471 participants who appear in
both the baseline and amyloid datasets. It has 2355 rows and 8
variables, with five rows per participant: one for each visit (baseline
and years 2, 4, 6, and 8), identified by the variable `visit`. Each row
gives the amyloid ratio measured at that visit (`amyloid_ratio`), along
with the participant’s baseline information (`current_age`, `sex`,
`education`, `apoe4`, and `age_at_onset`), which repeats across their
rows.
